theme: jekyll-theme-minimal
title: Michael David Adams
description: ":wave: Hey, I'm a student at KSU. I have my associate degree in computer science from GHC."
logo: /assets/michael.jpeg
show_downloads: false
