theme: jekyll-theme-minimal
title: Michael David Adams
description: ":wave: Hey, I'm a student at KSU. I have my associate degree in computer science from GHC. :robot: I love tech, the color blue, and Scooby-Doo."
logo: /assets/michael.jpeg
show_downloads: false
plugins:
  - jemoji
