title: Michael David Adams
description: "Student at KSU, with an associate degree in computer science from GHC. Interested in app development."
logo: /assets/michael.jpeg
show_downloads: false
page_excerpts: true
plugins:
  - jemoji
  - jekyll-remote-theme
