theme: jekyll-theme-minimal
title: Michael David Adams
description: "Hey! I'm a student at KSU, I have my associate degree in computer science from GHC. I am very interested in app development."
logo: /assets/michael.jpeg
show_downloads: false
plugins:
  - jemoji
